#https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router
[[redirects]]
  from = "http://localhost:3000/"
  to = "https://pomodoro-proglima.netlify.app/"
  status = 200
